---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-app-build
  namespace: tekton-pipelines
spec:
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    params:
    - name: url
      value: https://github.com/<your-username>/rails-app.git
    - name: revision
      value: main
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: build-and-push
    taskRef:
      name: kaniko
    runAfter:
    - clone
    params:
    - name: IMAGE
      value: docker.io/<your-dockerhub-username>/rails-app:latest
    - name: DOCKERFILE
      value: ./Dockerfile
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace