---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: <your-dockerhub-username>/rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rails-app-secrets
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
  namespace: default
spec:
  selector:
    app: rails-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP