---
apiVersion: v1
kind: Secret
metadata:
  name: rails-app-secrets
  namespace: default
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3JhaWxzX3VzZXI6cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL3JhaWxzX2FwcF9wcm9kdWN0aW9u
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=